name: Client Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Client/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alejandroamayaizquierdo/lhd.front.io:latest

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Build and d
          run: |
            docker build Client --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    deploy:
        needs: publish
        name: Deploy Image
        runs-on: ubuntu-latest

        steps:
          - name: SSH into Server and Deploy
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              password: ${{ secrets.SSH_PASSWORD }}
              script: cd ${{ secrets.CLIENT_WORK_DIR }} && docker-compose pull && docker-compose up --build -d && exit

          - name: cleanup
            run: rm -rf ~/.ssh
